### ISSUE TITLE
doesn't build with cabal - master

### ISSUE THREAD

**Issue by emmanueltouzery** [haskell-suite/haskell-packages#20]
In cabal git master (my version is marked as 1.21.1.0) the hugs support was removed:
https://github.com/haskell/cabal/commit/40f3601e17024f07e0da8e64d3dd390177ce908b

The latest version deployed on hackage though is 1.20.0.2 which still has the hugs support.

However trying to build haskell-packages with that development version of cabal fails due to that hugs support removal:

```haskell
src/Distribution/HaskellSuite/Packages.hs:381:25:
    Not in scope: ‘Info.hugsOptions’
    Perhaps you meant one of these:
      ‘Info.ccOptions’ (imported from Distribution.InstalledPackageInfo),
      ‘Info.ldOptions’ (imported from Distribution.InstalledPackageInfo)
```

**Comment by feuerbach** [comment]
Fixed, see #22
