### ISSUE TITLE
Cabal-3 update

### ISSUE THREAD

**Issue by ciez** [haskell-suite/haskell-packages#25]
are there any plans to update this package to be compatible with Cabal-3.0.*.*?

**Comment by niteria** [comment]
I became a maintainer of this when this was needed for my project at work. I no longer work there.

I'd be happy to merge a pull request or add you as a maintainer.

**Comment by ciez** [comment]
There is no urgency for me for the upgrade to Cabal 3.4.0.0

Could do a PR later.
